apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: construction 
spec:
  replicas: 3
  selector:
    matchLabels: 
      web: bank  
  template: 
    metadata:
      labels: 
        web: bank  
    spec: 
      containers: 
        - name: bank-site 
          image: wilses10/wilses10-digi-bankapp:1.0
          resources:
            limits:
              cpu: 50m
              memory: 250Mi
            requests:
              cpu: 25m
              memory: 120Mi
          ports: 
            - containerPort: 4545
--- 
apiVersion: v1 
kind: Service 
metadata: 
   name: construction   
spec: 
  selector: 
    web: bank 
  ports:
    port: 4546
    targetPort: 4545 
    protocol: TCP 
  type: ClusterIP 