apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: database  
spec:
  replicas: 3
  selector:
    matchLabels: 
      web: oracle  
  template: 
    metadata:
      labels: 
        web: oracle  
    spec: 
      containers: 
        - name: oracle-site 
          image: muralisocial123/test-web-oracle-example:1.0
          resources:
            limits:
              cpu: 50m
              memory: 250Mi
            requests:
              cpu: 25m
              memory: 120Mi
          ports: 
            - containerPort: 80
--- 
apiVersion: v1 
kind: Service 
metadata: 
   name: database    
spec: 
  selector: 
    web: oracle  
  ports:
    port: 81
    targetPort: 80 
    protocol: TCP 
  type: ClusterIP 