apiVersion: v1
kind: Pod
metadata:
  name: website1
  namespace: ocean
spec:
  containers:
    - name: bank
      image: wilses10/wilses10-digi-bankapp:1.0
      ports:
        - containerPort: 4545
    - name: foot
      image: wilses10/website:1.0
      ports:
        - containerPort: 3000
